--BEGIN
--    FOR t IN (SELECT table_name FROM user_tables) LOOP
--        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
--    END LOOP;
--END;
--
--SELECT sequence_name 
--FROM user_sequences;

--SELECT * FROM STUDY_COMMENT;
--SELECT * FROM ANNOUNCEMENT;
SELECT * FROM STUDY_RULE;
--SELECT * FROM BOARD_IMG;
SELECT * FROM STUDY;
--SELECT * FROM BOARD_TYPE;
--SELECT * FROM HIRE_INFO;
--SELECT * FROM HIRE_COMMENT;
--SELECT * FROM AUTH_KEY;
SELECT * FROM MEMBER;
--SELECT * FROM COMMENT;
--SELECT * FROM MAIN_CALENDAR;
--SELECT * FROM BOARD_LIKE;
--SELECT * FROM STUDY_IMAGE;
SELECT * FROM STUDY_MEMBER
WHERE MEMBER_NO = 19;
--SELECT * FROM STUDY_CALENDAR;
--SELECT * FROM STUDY_BOARD_IMG;
--SELECT * FROM BOARD;
--SELECT * FROM STUDY_BOARD;

COMMIT;

CREATE TABLE "STUDY_COMMENT" (
	"STUDY_COMMENT_NO"	NUMBER		NOT NULL,
	"STUDY_COMMENT_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"STUDY_COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"STUDY_COMMENT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"STUDY_BOARD_NO"	NUMBER		NOT NULL,
	"PARENT_STUDY_COMMENT_NO2"	NUMBER NULL
);

-- 스터디 게시판 댓글 시퀀스 만들기
CREATE SEQUENCE SEQ_STUDY_COMMENT_NO NOCACHE;

COMMENT ON COLUMN "STUDY_COMMENT"."STUDY_COMMENT_NO" IS '댓글 번호';

COMMENT ON COLUMN "STUDY_COMMENT"."STUDY_COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "STUDY_COMMENT"."STUDY_COMMENT_DEL_FL" IS '댓글 삭제 여부';

COMMENT ON COLUMN "STUDY_COMMENT"."STUDY_COMMENT_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "STUDY_COMMENT"."MEMBER_NO" IS '회원고유번호(FK)';

COMMENT ON COLUMN "STUDY_COMMENT"."STUDY_BOARD_NO" IS '게시글번호(FK)';

COMMENT ON COLUMN "STUDY_COMMENT"."PARENT_STUDY_COMMENT_NO2" IS '부모 댓글 번호(FK)';

CREATE TABLE "ANNOUNCEMENT" (
	"ANNOUNCE_NO"	NUMBER		NOT NULL,
	"ANNOUNCE_NAME"	NVARCHAR2(100)		NOT NULL,
	"ANNOUNCE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ANNOUNCE_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"ANNOUNCE_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"ANNOUNCE_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

-- 공지사항 시퀀스 만들기
CREATE SEQUENCE SEQ_ANNOUNCEMENT_NO NOCACHE;

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNOUNCE_NO" IS '게시글 번호';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNOUNCE_NAME" IS '게시글 제목';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNOUNCE_DATE" IS '작성 날짜';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNOUNCE_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNOUNCE_COUNT" IS '조회수';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNOUNCE_DEL_FL" IS '게시글 삭제 여부';

COMMENT ON COLUMN "ANNOUNCEMENT"."MEMBER_NO" IS '회원고유번호(FK)';

CREATE TABLE "STUDY_RULE" (
	"STUDY_NO"	NUMBER		NOT NULL,
	"RULE_CONTENT"	NVARCHAR2(2000)	DEFAULT '내규 내용'	NOT NULL
);

COMMENT ON COLUMN "STUDY_RULE"."STUDY_NO" IS '스터디고유번호(PK)';

COMMENT ON COLUMN "STUDY_RULE"."RULE_CONTENT" IS '내규 내용';

CREATE TABLE "BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"IMG_ORDER"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

-- 게시판 이미지 시퀀스 만들기
CREATE SEQUENCE SEQ_BOARD_IMG_NO NOCACHE;

COMMENT ON COLUMN "BOARD_IMG"."IMG_NO" IS '이미지 번호(PK)';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORIGINAL_NAME" IS '이미지 원본명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_RENAME" IS '이미지변경명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORDER" IS '이미지 순서';

COMMENT ON COLUMN "BOARD_IMG"."IMG_PATH" IS '이미지 경로';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글번호(FK)';

CREATE TABLE "STUDY" (
	"STUDY_NO"	NUMBER		NOT NULL,
	"STUDY_NAME"	NVARCHAR2(10)		NOT NULL,
	"STUDY_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"STUDY_MAX_COUNT"	NUMBER		NOT NULL,
	"STUDY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STUDY_TYPE"	NUMBER		NULL,
	"STUDY_PERIOD"	NUMBER	DEFAULT 0	NOT NULL
);

-- 스터디 시퀀스 만들기
CREATE SEQUENCE SEQ_STUDY_NO NOCACHE;

--DROP SEQUENCE SEQ_STUDY_NO;

COMMENT ON COLUMN "STUDY"."STUDY_NO" IS '스터디고유번호(PK)';

COMMENT ON COLUMN "STUDY"."STUDY_NAME" IS '스터디 이름';

COMMENT ON COLUMN "STUDY"."STUDY_DEL_FL" IS '스터디 활성화 여부';

COMMENT ON COLUMN "STUDY"."STUDY_MAX_COUNT" IS '스터디 인원수';

COMMENT ON COLUMN "STUDY"."STUDY_DATE" IS '스터디 생성일';

COMMENT ON COLUMN "STUDY"."STUDY_TYPE" IS '스터디 방향성';

COMMENT ON COLUMN "STUDY"."STUDY_PERIOD" IS '스터디운영기간_기본단위:개월_0:종강까지';

CREATE TABLE "BOARD_TYPE" (
	"BOARD_CODE"	NUMBER		NOT NULL,
	"BOARD_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CODE" IS '게시판종류코드번호(PK)';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NAME" IS '게시판명';

-- BOARD_TYPE 질문, 자유게시판 생성
INSERT INTO "BOARD_TYPE" VALUES (1, '질문 게시판');
INSERT INTO "BOARD_TYPE" VALUES (2, '자유 게시판');

CREATE TABLE "HIRE_INFO" (
	"HIRE_NO"	NUMBER		NOT NULL,
	"HIRE_READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"HIRE_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"HIRE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"HIRE_UPDATE"	DATE		NULL,
	"HIRE_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"STUDY_NO"	NUMBER		NOT NULL,
	"DAY_CAN_JOIN"	NVARCHAR2(1000)		NULL,
	"HIRE_COUNT"	NUMBER		NOT NULL,
	"HIRE_TITLE"	NVARCHAR2(1000)		NOT NULL
);

-- 구인 게시글 시퀀스 만들기
CREATE SEQUENCE SEQ_HIRE_INFO_NO NOCACHE;

COMMENT ON COLUMN "HIRE_INFO"."HIRE_NO" IS '구인 게시글 번호';

COMMENT ON COLUMN "HIRE_INFO"."HIRE_READ_COUNT" IS '게시글 조회수';

COMMENT ON COLUMN "HIRE_INFO"."HIRE_DEL_FL" IS '게시글 삭제 여부';

COMMENT ON COLUMN "HIRE_INFO"."HIRE_DATE" IS '게시글 작성 날짜';

COMMENT ON COLUMN "HIRE_INFO"."MEMBER_NO" IS '회원고유번호(FK)';

COMMENT ON COLUMN "HIRE_INFO"."HIRE_UPDATE" IS '게시글 수정 날짜';

COMMENT ON COLUMN "HIRE_INFO"."HIRE_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "HIRE_INFO"."STUDY_NO" IS '스터디고유번호(FK)';

COMMENT ON COLUMN "HIRE_INFO"."DAY_CAN_JOIN" IS '참가 가능 요일 정보';

COMMENT ON COLUMN "HIRE_INFO"."HIRE_COUNT" IS '현재 모집 인원';

COMMENT ON COLUMN "HIRE_INFO"."HIRE_TITLE" IS '게시글 제목';

CREATE TABLE "HIRE_COMMENT" (
	"HIRE_COMMENT_NO"	NUMBER		NOT NULL,
	"HIRE_COMMENT_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"HIRE_COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"HIRE_COMMENT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"HIRE_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

-- 구인 게시판 댓글 시퀀스 만들기
CREATE SEQUENCE SEQ_HIRE_COMMENT_NO NOCACHE;

COMMENT ON COLUMN "HIRE_COMMENT"."HIRE_COMMENT_NO" IS '댓글 번호';

COMMENT ON COLUMN "HIRE_COMMENT"."HIRE_COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "HIRE_COMMENT"."HIRE_COMMENT_DEL_FL" IS '댓글 삭제 여부';

COMMENT ON COLUMN "HIRE_COMMENT"."HIRE_COMMENT_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "HIRE_COMMENT"."HIRE_NO" IS '구인 게시글 번호(FK)';

COMMENT ON COLUMN "HIRE_COMMENT"."MEMBER_NO" IS '회원고유번호(FK)';

CREATE TABLE "AUTH_KEY" (
	"AUTH_KEY_NO"	NUMBER		NOT NULL,
	"EMAIL"	NVARCHAR2(50)		NOT NULL,
	"AUTH_KEY"	CHAR(6)		NOT NULL,
	"CREATE_TIME"	DATE	DEFAULT SYSDATE	NOT NULL
);

SELECT * FROM "BOARD";
SELECT * FROM "STUDY";
SELECT * FROM "STUDY_MEMBER";
SELECT * FROM "ANNOUNCEMENT";
DELETE FROM "STUDY"
WHERE STUDY_NO = 24;

UPDATE "ANNOUNCEMENT" SET
ANNOUNCE_NAME = '[인터페이스 구현] 보충수업/첨삭지도일지'
WHERE ANNOUNCE_NO = 3;


ALTER TABLE "ANNOUNCEMENT" ADD ANNOUNCE_UPDATE_DATE DATE;
COMMENT ON COLUMN "ANNOUNCEMENT"."ANNOUNCE_UPDATE_DATE" IS '게시글 수정 날짜';

COMMIT;

SELECT 
    STUDY_NO,
    COUNT(MEMBER_NO) AS MEMBER_COUNT
FROM 
    STUDY_MEMBER
GROUP BY 
    STUDY_NO;

COMMIT;

-- 인증키 시퀀스 만들기
CREATE SEQUENCE SEQ_AUTH_KEY_NO NOCACHE;

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_NO" IS '인증키구분번호(PK)';

COMMENT ON COLUMN "AUTH_KEY"."EMAIL" IS '인증이메일';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY" IS '인증번호';

COMMENT ON COLUMN "AUTH_KEY"."CREATE_TIME" IS '인증번호생성';

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_EMAIL"	NVARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	NVARCHAR2(100)		NOT NULL,
	"MEMBER_NICKNAME"	NVARCHAR2(10)		NOT NULL,
	"MEMBER_TEL"	CHAR(11)		NOT NULL,
	"MEMBER_ADDRESS"	NVARCHAR2(300)		NOT NULL,
	"PROFILE_IMG"	VARCHAR2(300)		NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"AUTHORITY"	NUMBER	DEFAULT 0	NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_MAJOR"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_INTRODUCE"	NVARCHAR2(100)		NULL,
	"MEMBER_NAME"	NVARCHAR2(5)		NOT NULL
);

ALTER TABLE "MEMBER" MODIFY "MEMBER_ADDRESS" NULL;



-- 회원번호 시퀀스 만들기
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

--DROP SEQUENCE SEQ_MEMBER_NO;

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원고유번호(PK)';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '회원주소';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필이미지';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '탈퇴여부(Y/N)';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '회원등급권한_관리자등급:1';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_MAJOR" IS '전공 여부';

COMMENT ON COLUMN "MEMBER"."MEMBER_INTRODUCE" IS '자기소개';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원 이름';

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"PARENT_COMMENT_NO"	NUMBER NULL,
	"COMMENT_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"COMMENT_WRITTEN_DATE"	DATE		NOT NULL,
	"COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

-- 게시판 댓글 시퀀스 만들기
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE;

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글번호(PK)';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원고유번호(FK)';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글번호(FK)';

COMMENT ON COLUMN "COMMENT"."PARENT_COMMENT_NO" IS '부모댓글번호(FK)';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_WRITTEN_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '댓글 삭제 여부';

CREATE TABLE "MAIN_CALENDAR" (
	"MAIN_CALENDAR_NO"	NUMBER		NOT NULL,
	"MAIN_CALENDAR_TITLE"	NVARCHAR2(100)		NOT NULL,
	"MAIN_START"	DATE		NOT NULL,
	"MAIN_END"	DATE		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

-- 학사일정 시퀀스 만들기
CREATE SEQUENCE SEQ_MAIN_CALENDAR_NO NOCACHE;

COMMENT ON COLUMN "MAIN_CALENDAR"."MAIN_CALENDAR_NO" IS '일정 번호';

COMMENT ON COLUMN "MAIN_CALENDAR"."MAIN_CALENDAR_TITLE" IS '일정 이름';

COMMENT ON COLUMN "MAIN_CALENDAR"."MAIN_START" IS '일정 시작일';

COMMENT ON COLUMN "MAIN_CALENDAR"."MAIN_END" IS '일정 종료일';

COMMENT ON COLUMN "MAIN_CALENDAR"."MEMBER_NO" IS '회원고유번호(FK)';

CREATE TABLE "BOARD_LIKE" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_LIKE"."BOARD_NO" IS '게시글번호(PK)';

COMMENT ON COLUMN "BOARD_LIKE"."MEMBER_NO" IS '회원고유번호(PK)';

CREATE TABLE "STUDY_IMAGE" (
	"STUDY_IMG_NO"	NUMBER		NOT NULL,
	"STUDY_IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"STUDY_IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"STUDY_IMG_ORDER"	NUMBER		NOT NULL,
	"STUDY_IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"STUDY_NO"	NUMBER		NOT NULL
);

-- 스터디 게시판 이미지 시퀀스 만들기
CREATE SEQUENCE SEQ_STUDY_IMG_NO NOCACHE;

COMMENT ON COLUMN "STUDY_IMAGE"."STUDY_IMG_NO" IS '이미지 번호';

COMMENT ON COLUMN "STUDY_IMAGE"."STUDY_IMG_ORIGINAL_NAME" IS '이미지 원본명';

COMMENT ON COLUMN "STUDY_IMAGE"."STUDY_IMG_RENAME" IS '이미지 변경명';

COMMENT ON COLUMN "STUDY_IMAGE"."STUDY_IMG_ORDER" IS '이미지 순서';

COMMENT ON COLUMN "STUDY_IMAGE"."STUDY_IMG_PATH" IS '이미지 경로';

COMMENT ON COLUMN "STUDY_IMAGE"."STUDY_NO" IS '스터디고유번호(PK)';

CREATE TABLE "STUDY_MEMBER" (
	"STUDY_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"STUDY_CAP"	CHAR(1)		NULL
);

COMMENT ON COLUMN "STUDY_MEMBER"."STUDY_NO" IS '스터디고유번호(FK)';

COMMENT ON COLUMN "STUDY_MEMBER"."MEMBER_NO" IS '회원고유번호(FK)';

COMMENT ON COLUMN "STUDY_MEMBER"."STUDY_CAP" IS '팀장 여부';

CREATE TABLE "STUDY_CALENDAR" (
	"CALENDAR_NO"	NUMBER		NOT NULL,
	"CALENDAR_TITLE"	NVARCHAR2(100)		NOT NULL,
	"START"	DATE		NOT NULL,
	"END"	DATE		NOT NULL,
	"STUDY_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

-- 스터디 일정 공유 시퀀스 만들기
CREATE SEQUENCE SEQ_STUDY_CALENDAR_NO NOCACHE;

COMMENT ON COLUMN "STUDY_CALENDAR"."CALENDAR_NO" IS '일정 번호';

COMMENT ON COLUMN "STUDY_CALENDAR"."CALENDAR_TITLE" IS '일정 이름';

COMMENT ON COLUMN "STUDY_CALENDAR"."START" IS '일정 시작일';

COMMENT ON COLUMN "STUDY_CALENDAR"."END" IS '일정 종료일';

COMMENT ON COLUMN "STUDY_CALENDAR"."STUDY_NO" IS '스터디고유번호(FK)';

COMMENT ON COLUMN "STUDY_CALENDAR"."MEMBER_NO" IS '회원고유번호(FK)';

CREATE TABLE "STUDY_BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"IMG_ORDER"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"STUDY_BOARD_NO"	NUMBER		NOT NULL
);

-- 스터디 게시판 이미지 시퀀스 만들기
CREATE SEQUENCE SEQ_STUDY_BOARD_IMG_NO NOCACHE;

COMMENT ON COLUMN "STUDY_BOARD_IMG"."IMG_NO" IS '이미지 번호(PK)';

COMMENT ON COLUMN "STUDY_BOARD_IMG"."IMG_ORIGINAL_NAME" IS '이미지 원본명';

COMMENT ON COLUMN "STUDY_BOARD_IMG"."IMG_RENAME" IS '이미지변경명';

COMMENT ON COLUMN "STUDY_BOARD_IMG"."IMG_ORDER" IS '이미지 순서';

COMMENT ON COLUMN "STUDY_BOARD_IMG"."IMG_PATH" IS '이미지 경로';

COMMENT ON COLUMN "STUDY_BOARD_IMG"."STUDY_BOARD_NO" IS '게시글번호(FK)';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(100)		NOT NULL,
	"BOARD_CODE"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_UPDATE_DATE"	DATE		NULL,
	"BOARD_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);
SELECT * FROM STUDY_CALENDAR;

-- 게시판 시퀀스 만들기
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE;

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글번호(PK)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시판제목';

COMMENT ON COLUMN "BOARD"."BOARD_CODE" IS '게시판종류코드번호(FK)';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원고유번호(FK)';

COMMENT ON COLUMN "BOARD"."BOARD_WRITE_DATE" IS '게시글 작성 날짜';

COMMENT ON COLUMN "BOARD"."BOARD_UPDATE_DATE" IS '게시글 수정일';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글 삭제 여부';

CREATE TABLE "STUDY_BOARD" (
	"STUDY_BOARD_NO"	NUMBER		NOT NULL,
	"STUDY_BOARD_TITLE"	NVARCHAR2(100)		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"STUDY_NO"	NUMBER		NOT NULL,
	"STUDY_BOARD_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STUDY_BOARD_UPDATE_DATE"	DATE		NULL,
	"STUDY_BOARD_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"STUDY_BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

-- 스터디 게시판 시퀀스 만들기
CREATE SEQUENCE SEQ_STUDY_BOARD_NO NOCACHE;

COMMENT ON COLUMN "STUDY_BOARD"."STUDY_BOARD_NO" IS '게시글번호(PK)';

COMMENT ON COLUMN "STUDY_BOARD"."STUDY_BOARD_TITLE" IS '게시판제목';

COMMENT ON COLUMN "STUDY_BOARD"."MEMBER_NO" IS '회원고유번호(FK)';

COMMENT ON COLUMN "STUDY_BOARD"."STUDY_NO" IS '스터디고유번호(FK)';

COMMENT ON COLUMN "STUDY_BOARD"."STUDY_BOARD_WRITE_DATE" IS '게시글 작성 날짜';

COMMENT ON COLUMN "STUDY_BOARD"."STUDY_BOARD_UPDATE_DATE" IS '게시글 수정일';

COMMENT ON COLUMN "STUDY_BOARD"."STUDY_BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "STUDY_BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "STUDY_BOARD"."STUDY_BOARD_DEL_FL" IS '게시글 삭제 여부';

ALTER TABLE "STUDY_COMMENT" ADD CONSTRAINT "PK_STUDY_COMMENT" PRIMARY KEY (
	"STUDY_COMMENT_NO"
);

ALTER TABLE "ANNOUNCEMENT" ADD CONSTRAINT "PK_ANNOUNCEMENT" PRIMARY KEY (
	"ANNOUNCE_NO"
);

ALTER TABLE "STUDY_RULE" ADD CONSTRAINT "PK_STUDY_RULE" PRIMARY KEY (
	"STUDY_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "STUDY" ADD CONSTRAINT "PK_STUDY" PRIMARY KEY (
	"STUDY_NO"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_CODE"
);

ALTER TABLE "HIRE_INFO" ADD CONSTRAINT "PK_HIRE_INFO" PRIMARY KEY (
	"HIRE_NO"
);

ALTER TABLE "HIRE_COMMENT" ADD CONSTRAINT "PK_HIRE_COMMENT" PRIMARY KEY (
	"HIRE_COMMENT_NO"
);

ALTER TABLE "AUTH_KEY" ADD CONSTRAINT "PK_AUTH_KEY" PRIMARY KEY (
	"AUTH_KEY_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "MAIN_CALENDAR" ADD CONSTRAINT "PK_MAIN_CALENDAR" PRIMARY KEY (
	"MAIN_CALENDAR_NO"
);

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "PK_BOARD_LIKE" PRIMARY KEY (
	"BOARD_NO",
	"MEMBER_NO"
);

ALTER TABLE "STUDY_IMAGE" ADD CONSTRAINT "PK_STUDTY_IMAGE" PRIMARY KEY (
	"STUDY_IMG_NO"
);

ALTER TABLE "STUDY_MEMBER" ADD CONSTRAINT "PK_STUDY_MEMBER" PRIMARY KEY (
	"STUDY_NO",
	"MEMBER_NO"
);

ALTER TABLE "STUDY_CALENDAR" ADD CONSTRAINT "PK_STUDY_CALENDAR" PRIMARY KEY (
	"CALENDAR_NO"
);

ALTER TABLE "STUDY_BOARD_IMG" ADD CONSTRAINT "PK_STUDY_BOARD_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "STUDY_BOARD" ADD CONSTRAINT "PK_STUDY_BOARD" PRIMARY KEY (
	"STUDY_BOARD_NO"
);

ALTER TABLE "STUDY_COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_STUDY_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "STUDY_COMMENT" ADD CONSTRAINT "FK_STUDY_BOARD_TO_STUDY_COMMENT_1" FOREIGN KEY (
	"STUDY_BOARD_NO"
)
REFERENCES "STUDY_BOARD" (
	"STUDY_BOARD_NO"
) ON DELETE CASCADE;

ALTER TABLE "STUDY_COMMENT" ADD CONSTRAINT "FK_STUDY_COMMENT_TO_STUDY_COMMENT_1" FOREIGN KEY (
	"PARENT_STUDY_COMMENT_NO2"
)
REFERENCES "STUDY_COMMENT" (
	"STUDY_COMMENT_NO"
);

ALTER TABLE "ANNOUNCEMENT" ADD CONSTRAINT "FK_MEMBER_TO_ANNOUNCEMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "STUDY_RULE" ADD CONSTRAINT "FK_STUDY_TO_STUDY_RULE_1" FOREIGN KEY (
	"STUDY_NO"
)
REFERENCES "STUDY" (
	"STUDY_NO"
) ON DELETE CASCADE;

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
) ON DELETE CASCADE;

ALTER TABLE "HIRE_INFO" ADD CONSTRAINT "FK_MEMBER_TO_HIRE_INFO_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "HIRE_INFO" ADD CONSTRAINT "FK_STUDY_TO_HIRE_INFO_1" FOREIGN KEY (
	"STUDY_NO"
)
REFERENCES "STUDY" (
	"STUDY_NO"
) ON DELETE CASCADE;

ALTER TABLE "HIRE_COMMENT" ADD CONSTRAINT "FK_HIRE_INFO_TO_HIRE_COMMENT_1" FOREIGN KEY (
	"HIRE_NO"
)
REFERENCES "HIRE_INFO" (
	"HIRE_NO"
) ON DELETE CASCADE;

ALTER TABLE "HIRE_COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_HIRE_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
) ON DELETE CASCADE;

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" FOREIGN KEY (
	"PARENT_COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "MAIN_CALENDAR" ADD CONSTRAINT "FK_MEMBER_TO_MAIN_CALENDAR_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_BOARD_TO_BOARD_LIKE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
) ON DELETE CASCADE;

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "STUDY_IMAGE" ADD CONSTRAINT "FK_STUDY_TO_STUDTY_IMAGE_1" FOREIGN KEY (
	"STUDY_NO"
)
REFERENCES "STUDY" (
	"STUDY_NO"
) ON DELETE CASCADE;

ALTER TABLE "STUDY_MEMBER" ADD CONSTRAINT "FK_STUDY_TO_STUDY_MEMBER_1" FOREIGN KEY (
	"STUDY_NO"
)
REFERENCES "STUDY" (
	"STUDY_NO"
) ON DELETE CASCADE;

ALTER TABLE "STUDY_MEMBER" ADD CONSTRAINT "FK_MEMBER_TO_STUDY_MEMBER_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "STUDY_CALENDAR" ADD CONSTRAINT FK_STUDY_CALENDAR_STUDY_MEMBER
FOREIGN KEY ("STUDY_NO", "MEMBER_NO")
REFERENCES "STUDY_MEMBER" ("STUDY_NO", "MEMBER_NO")
ON DELETE CASCADE;

ALTER TABLE "STUDY_BOARD_IMG" ADD CONSTRAINT "FK_STUDY_BOARD_TO_STUDY_BOARD_IMG_1" FOREIGN KEY (
	"STUDY_BOARD_NO"
)
REFERENCES "STUDY_BOARD" (
	"STUDY_BOARD_NO"
) ON DELETE CASCADE;

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1" FOREIGN KEY (
	"BOARD_CODE"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_CODE"
) ON DELETE CASCADE;

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "STUDY_BOARD" ADD CONSTRAINT "FK_MEMBER_TO_STUDY_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "STUDY_BOARD" ADD CONSTRAINT "FK_STUDY_TO_STUDY_BOARD_1" FOREIGN KEY (
	"STUDY_NO"
)
REFERENCES "STUDY" (
	"STUDY_NO"
) ON DELETE CASCADE;

COMMIT;